/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ssinghal' at '4/17/15 7:15 PM' with Gradle 2.3
 *
 * @author ssinghal, @date 4/17/15 7:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
